### ISSUE TITLE
Cannot access submodule repo

### ISSUE THREAD

**Issue by RussellWang9** [YanB25/Patronus#1]
Cannot access submodule DataFrame git@git.tsinghua.edu.cn:yanb20/dataframe.git.

**Comment by YanB25** [comment]
Just use https://github.com/hosseinmoein/DataFrame.
You can change the url of DataFrame submodule by modifying `.gitmodules` directly.

**Comment by RussellWang9** [comment]
I tried. Then I got this error:
```
/home/zwx/Patronus/bench/bench_allocator.cpp:1228:8: error: ‘using StrDataFrame = hmdf::StdDataFrame<std::__cxx11::basic_string<char> >’ {aka ‘class hmdf::DataFrame<std::__cxx11::basic_string<char>, hmdf::HeteroVector>’} has no member named ‘consolidate’
     df.consolidate<size_t, size_t, double>(
```

**Comment by YanB25** [comment]
Try this commit of DataFrame `f7970f1d8a0e1a6c2570c6734f6e82f63bafcd9f`

**Comment by RussellWang9** [comment]
Thanks. That works fine for me.
